### ISSUE TITLE
Why doesn't keyboardWillShow fire with resizeApp = false?

### ISSUE THREAD

**Issue by hotzenklotz** [mhweiner/CordovaiOSKeyboardPlugin#4]
Hi,

the `keyboardWillShow` event does not fire when the the `resizeApp` Property is not set to `true`. Hence, by default this event never fires. See line 62 for reference:
https://github.com/mhweiner/CordovaiOSKeyboardPlugin/blob/master/src/ios/KeyboardPlugin.m#L62

Is this intentional or a bug? Why would you not want the event to fire in the different resizing modes? I think it makes sense to always get this event. The `keyboardDidShow` event always fires, regardless of the resizing settings.

**Comment by mhweiner** [comment]
This is a good point. I will modify the code to do this.

**Comment by mhweiner** [comment]
This has been fixed. It was definitely a design flaw (and a big one!). Thanks for pointing that out. Sorry for the late fix, I've been quite busy...

It also auto-instantiates now, so you don't need Keyboard.setup() anymore. Before you update this plugin, please review all of the changes, since I made some pretty major ones. You should remove any reference to Keyboard.setup() and Keyboard.resizeApp(), since they no longer exist. iOS7.1, along with some other issues people experienced forced me to remove the resizeApp() functionality.
